version: 2.1
orbs:
  win: circleci/windows@5
  matlab: mathworks/matlab@1
jobs:
  build:
    executor: win/default
    environment:
      MATLAB_LOG_DIR: ~/project/logs
      MW_DIAGNOSTIC_DEST: file
      MW_DIAGNOSTIC_SPEC: cppmicroservices::framework.*=all;install.*=all;
      MW_VERBOSE_HTTPCLIENT_CORE: 1
    steps:
      - run:
          command: echo $0
          shell: bash
      # - checkout
      # - matlab/install:
      #     products: Optimization_Toolbox Curve_Fitting_Toolbox
      # - matlab/run-tests:
      #     source-folder: code
      # - store_artifacts:
      #     path: ~/project/logs
      #     destination: matlab-logs
      #     when: always
