name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  myjob:
    strategy:
      matrix:
        os: [ubuntu-latest] # [windows-latest, ubuntu-latest, macos-latest, macos-13]
      fail-fast: false
    runs-on: ${{ matrix.os }}

    env:
      MATLAB_LOG_DIR: ${{ github.workspace }}/logs
      MW_DIAGNOSTIC_DEST: file
      MW_DIAGNOSTIC_SPEC: cppmicroservices::framework.*=all;install.*=all;
      MW_VERBOSE_HTTPCLIENT_CORE: 1
      
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        
      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v2

      - name: Print MPM logs
        run: |
          ls -l "${{ env.MATLAB_LOG_DIR }}"
          cat "${{ env.MATLAB_LOG_DIR }}/*"
        shell: bash
