name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  myjob:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest, macos-13]
      fail-fast: false
    runs-on: ${{ matrix.os }}

    env:
      MATLAB_LOG_DIR: ${{ github.workspace }}/logs
      MW_DIAGNOSTIC_DEST: file
      MW_DIAGNOSTIC_SPEC: cppmicroservices::framework.*=all;install.*=all;
      MW_VERBOSE_HTTPCLIENT_CORE: 1
      
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        
      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v2

      - name: Print MPM logs for debugging
        run: |
          for file in "${{ env.MATLAB_LOG_DIR }}"/*; do [ -f "$file" ] && echo "==> $file <==" && cat "$file"; done
        shell: bash
