name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  myjob:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest, macos-13]
      fail-fast: false
    runs-on: ${{ matrix.os }}

    env:
      MATLAB_LOG_DIR: ${{ github.workspace }}/logs
      MW_DIAGNOSTIC_DEST: file
      MW_DIAGNOSTIC_SPEC: cppmicroservices::framework.*=all;install.*=all;
      MW_VERBOSE_HTTPCLIENT_CORE: 1
      
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        
      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v2

      - name: Upload MPM and MATLAB logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: matlab-logs-${{ matrix.os }}
          path: ${{ env.MATLAB_LOG_DIR }}
          if-no-files-found: ignore
